### ISSUE TITLE
Does not show recent (e.g., 23.x) symbols/packages

### ISSUE THREAD

**Issue by rvanbekkum** [sergiogp1/BC-AL-Packages#8]
The AL: Download Packages command does not allow you to download 23.x symbols/packages. It only lists 22.x symbols.

**Comment by jorispoppe** [comment]
I managed to download them by installing the extension.
Maybe you need to update your artifact versions? With the AL: Download artifact versions command?
Otherwise, there might be an error in the update of the version file.

**Comment by rvanbekkum** [comment]
I think that was the problem, now I get 24.0 symbols as well.

I did not know there was a command to refresh ;) Just reinstalled the extension to give it another try 😊
